//go:build darwin

package supervise

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// The macOS backend: a generated seatbelt (SBPL) profile applied with
// sandbox-exec.
//
// sandbox-exec is deprecated by Apple and has been for years, while remaining
// the only way to apply a profile to an arbitrary child process from userland.
// That is precisely why NewSandbox refuses to return a sandbox it has not just
// watched work (see canary): a confinement mechanism that quietly stops
// functioning after an OS update, leaving a profile that parses and enforces
// nothing, is worse than no confinement at all — the operator would still be
// told they were protected.

const sandboxExec = "/usr/bin/sandbox-exec"

// BuildProfile renders an SBPL profile for spec.
//
// Two rules govern every path written into it, both established empirically
// against the real sandbox-exec, and both silent when broken:
//
//   - **Paths must be fully resolved.** Seatbelt matches the kernel's own view,
//     so a rule naming /tmp/x matches nothing on a machine where /tmp is a
//     symlink to /private/tmp — which is every macOS machine. Callers pass paths
//     through ResolvePath before they get here.
//   - **`literal` names a file, `subpath` names a directory tree.** Naming a
//     file with subpath matches nothing. Nothing warns; the profile loads and
//     enforces silently less than it says.
func BuildProfile(spec SandboxSpec) string {
	var b strings.Builder
	b.WriteString("(version 1)\n")
	b.WriteString(";; Generated by vaultysclaw-sensor. Deny-list, not general confinement:\n")
	b.WriteString(";; everything not named below is permitted. See internal/supervise/sandbox.go.\n")
	b.WriteString("(allow default)\n")

	for _, p := range spec.DenyAll {
		fmt.Fprintf(&b, "(deny file-read* file-write* %s)\n", sbPath(p))
	}
	for _, p := range spec.DenyWrite {
		// Read stays permitted: the harness is launched with --settings pointing
		// at one of these and must read it to install the hook.
		fmt.Fprintf(&b, "(deny file-write* %s)\n", sbPath(p))
	}
	return b.String()
}

// sbEscape escapes a path for an SBPL string literal.
//
// Hand-rolled rather than %q, which would also escape non-ASCII bytes as Go \u
// sequences — a path with an accent in it would then name a different file, or
// none. SBPL literals are C-like, so a backslash and a quote are the only two
// characters that need it.
var sbEscape = strings.NewReplacer(`\`, `\\`, `"`, `\"`)

func sbPath(p string) string {
	quoted := sbEscape.Replace(p)
	if pathKind(p) {
		return fmt.Sprintf(`(subpath "%s")`, quoted)
	}
	return fmt.Sprintf(`(literal "%s")`, quoted)
}

// NewSandbox writes the profile, proves it actually confines, and returns a
// wrapper. It refuses rather than degrading: a caller that asked for confinement
// and got a no-op must find out here, not from an incident.
func NewSandbox(spec SandboxSpec, dir string) (*Sandbox, error) {
	if _, err := os.Stat(sandboxExec); err != nil {
		return nil, ErrSandboxUnavailable{Platform: "darwin", Why: sandboxExec + " is not present"}
	}

	// The canary: a file this process creates, denies, and then tries to read
	// through the real mechanism. Unlike probing one of the operator's own floor
	// paths, it exists for certain, so a failure to read it can only mean the
	// profile worked — there is no "the file was missing anyway" reading of the
	// result.
	canaryDir, err := os.MkdirTemp(dir, ".vaultysclaw-sandbox-check")
	if err != nil {
		return nil, fmt.Errorf("supervise: preparing the sandbox self-test: %w", err)
	}
	defer os.RemoveAll(canaryDir)
	resolvedCanaryDir, err := ResolvePath(canaryDir, "")
	if err != nil {
		return nil, err
	}
	canary := filepath.Join(resolvedCanaryDir, "canary")
	if err := os.WriteFile(canary, []byte("canary"), 0o600); err != nil {
		return nil, fmt.Errorf("supervise: preparing the sandbox self-test: %w", err)
	}

	testSpec := spec
	testSpec.DenyAll = append(append([]string{}, spec.DenyAll...), canary)
	testProfile := filepath.Join(resolvedCanaryDir, "check.sb")
	if err := os.WriteFile(testProfile, []byte(BuildProfile(testSpec)), 0o600); err != nil {
		return nil, err
	}
	if err := runCanary(testProfile, canary); err != nil {
		return nil, err
	}

	// The real profile, written where it survives the self-test's cleanup.
	profile, err := os.CreateTemp(dir, ".vaultysclaw-*.sb")
	if err != nil {
		return nil, fmt.Errorf("supervise: writing the sandbox profile: %w", err)
	}
	profilePath := profile.Name()
	if _, err := profile.WriteString(BuildProfile(spec)); err != nil {
		profile.Close()
		os.Remove(profilePath)
		return nil, err
	}
	profile.Close()

	return &Sandbox{
		Wrap: func(command []string) []string {
			return append([]string{sandboxExec, "-f", profilePath, "--"}, command...)
		},
		Description: fmt.Sprintf("seatbelt via %s — %d paths denied outright, %d write-protected",
			sandboxExec, len(spec.DenyAll), len(spec.DenyWrite)),
		cleanup: func() { os.Remove(profilePath) },
	}, nil
}

// runCanary proves the profile is enforced, right now, on this machine.
//
// Both directions are checked. Reading the canary *outside* the sandbox must
// succeed — otherwise a permissions problem would masquerade as a working
// confinement — and reading it *inside* must fail. Only the pair proves
// anything; either alone is satisfied by something being broken.
func runCanary(profilePath, canary string) error {
	if err := exec.Command("/bin/cat", canary).Run(); err != nil {
		return fmt.Errorf("supervise: the sandbox self-test is inconclusive — the canary is unreadable even unconfined: %w", err)
	}
	out, err := exec.Command(sandboxExec, "-f", profilePath, "--", "/bin/cat", canary).CombinedOutput()
	if err == nil {
		return fmt.Errorf(
			"supervise: refusing to launch — the seatbelt profile loaded but did not deny a path it names. "+
				"Confinement is not in force on this machine (sandbox-exec is deprecated and its behaviour has changed before). "+
				"Self-test output: %q", strings.TrimSpace(string(out)))
	}
	return nil
}
