/**
 * Demo Skill: Report Writer
 *
 * Loaded by the report-agent to demonstrate file_access capability.
 * Writes structured markdown reports to the demo workspace directory.
 *
 * Tools:
 *   - write_report: Saves a structured report as a markdown file
 *   - list_reports: Lists previously generated reports
 */

import { createTool } from "@mastra/core/tools";
import { z } from "zod";
import fs from "fs";
import path from "path";

const REPORTS_DIR = process.env.AGENT_WORKSPACE_ROOT
  ? path.resolve(process.env.AGENT_WORKSPACE_ROOT)
  : path.resolve("./demo/workspace");

function ensureDir(dir) {
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
}

export const skill = {
  name: "report-writer",
  description: "Write structured markdown reports to the workspace for review.",
  version: "1.0.0",

  systemPromptExtension: `
You have access to report writing tools. When asked to produce a report:
1. Structure it with clear headings (##), bullet points, and a summary section.
2. Always include: Title, Date, Executive Summary, Findings, and Recommendations.
3. Use write_report to persist the report to disk.
4. Confirm the file path to the user when done.
`.trim(),

  tools: [
    {
      name: "write_report",
      capability: "file_access",
      requiresApproval: true, // shows approval gate in the demo
      tool: createTool({
        id: "write_report",
        description:
          "Write a markdown report file to the workspace. " +
          "Returns the file path and byte size of the saved report.",
        inputSchema: z.object({
          filename: z
            .string()
            .regex(/^[\w\-. ]+\.md$/, "Must be a .md filename, no path separators")
            .describe("Report filename (e.g. security-audit-2026.md)"),
          title: z.string().describe("Report title"),
          content: z.string().describe("Full markdown content of the report"),
        }),
        execute: async ({ filename, title, content }) => {
          ensureDir(REPORTS_DIR);
          const safeFile = path.basename(filename);
          const filePath = path.join(REPORTS_DIR, safeFile);

          const header = `# ${title}\n\n_Generated by VaultysClaw report-agent — ${new Date().toISOString()}_\n\n---\n\n`;
          const fullContent = header + content;

          fs.writeFileSync(filePath, fullContent, "utf-8");

          return {
            success: true,
            filePath,
            bytes: Buffer.byteLength(fullContent, "utf-8"),
            message: `Report saved to ${filePath}`,
          };
        },
      }),
    },
    {
      name: "list_reports",
      capability: "file_access",
      requiresApproval: false,
      tool: createTool({
        id: "list_reports",
        description: "List all report files in the workspace directory.",
        inputSchema: z.object({}),
        execute: async () => {
          ensureDir(REPORTS_DIR);
          const files = fs
            .readdirSync(REPORTS_DIR)
            .filter((f) => f.endsWith(".md"))
            .map((f) => {
              const stat = fs.statSync(path.join(REPORTS_DIR, f));
              return { filename: f, bytes: stat.size, modified: stat.mtime.toISOString() };
            });
          return { reportsDir: REPORTS_DIR, reports: files };
        },
      }),
    },
  ],
};
