/**
 * Regenerates conformance/kindconfig-fixture.json — a `harness` kindConfig
 * signed by the TypeScript control plane, for the Go verifier to check
 * (docs/HARNESS_SUPERVISOR.md §12).
 *
 * This fixture exists because of a specific near-miss. The unsigned copy of a
 * kindConfig arrives as JSON on the socket and the signed one arrives as the
 * msgpack body `signCert` wraps — the same fields in two encodings. The Go
 * struct originally carried only `json:` tags, so the msgpack decode produced a
 * struct of nil pointers. Every field being a pointer, nil reads as *absent*,
 * and "absent" is applied as "no change" — so a perfectly valid signed
 * configuration would have been verified, decoded, and then silently done
 * nothing, with no error on either side.
 *
 * That is the failure mode this whole conformance directory exists for: not a
 * crash, but two implementations quietly disagreeing about what a byte means.
 *
 * Uses the same fixed throwaway key as the other two fixtures, so a host can pin
 * one anchor and verify all three.
 *
 * Run from the repo root:
 *
 *     pnpm tsx conformance/generate-kindconfig-fixture.ts
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { VaultysId, crypto as vaultysCrypto } from "@vaultys/id";
import { signCert } from "../packages/policy/src/index";
import {
  DEFAULT_HARNESS_KIND_CONFIG,
  type HarnessKindConfig,
} from "../packages/controlplane/lib/harness-kind";

/** Same deterministic throwaway key as the other generators. */
const TEST_SECRET_SEED = Buffer.alloc(32, 0x2a);

const OUT_PATH = fileURLToPath(new URL("./kindconfig-fixture.json", import.meta.url));

async function main() {
  const server = await VaultysId.machineFromEntropy(TEST_SECRET_SEED);

  // Deliberately *not* the defaults: every field carries a value distinguishable
  // from its zero, so a field the Go side fails to decode shows up as a wrong
  // answer rather than as a coincidentally-correct one. `maxStatusAgeSeconds` is
  // positive for the same reason — 0 and -1 are both meaningful here, and a
  // decode failure yielding either would look plausible.
  const config: HarnessKindConfig = {
    ...DEFAULT_HARNESS_KIND_CONFIG,
    mode: "explicit",
    sandbox: "require",
    maxStatusAgeSeconds: 3600,
    resourceRules: [
      { id: "deny-ssh", subject: "any", resources: ["file:///Users/fx/.ssh/*"], effect: "deny" },
    ],
  };

  const token = await signCert(server, config as unknown as Record<string, unknown>);

  const fixture = {
    $comment: [
      "Generated by conformance/generate-kindconfig-fixture.ts — do not hand-edit.",
      "A harness kindConfig signed by packages/controlplane/lib/actor-config.ts's",
      "signKindConfig, verified by vaultysclaw-sensor/internal/supervise's",
      "VerifiedConfig (see kindconfig_fixture_test.go).",
      "",
      "Pins the one thing nothing else would catch: that the msgpack body signCert",
      "produces decodes into the Go struct's fields. Those fields are pointers, so a",
      "tag mismatch yields nil — which means 'absent', which is applied as 'no",
      "change'. A valid signed configuration would then verify, decode, and silently",
      "do nothing.",
      "",
      "The signing key is a fixed throwaway test key and grants nothing real.",
    ],
    version: 1,
    serverIdBase64: vaultysCrypto.Buffer.from(server.id).toString("base64"),
    serverDid: server.did,
    token,
    expectedConfig: config,
  };

  writeFileSync(OUT_PATH, JSON.stringify(fixture, null, 2) + "\n");
  console.log(`wrote ${OUT_PATH}`);
  console.log(`  mode=${config.mode} sandbox=${config.sandbox}, token ${token.length} chars`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
