/**
 * Regenerates conformance/rules-fixture.json — a proxy rule set signed by the
 * TypeScript control plane, for the Go verifier to check
 * (docs/PROXY_ARCHITECTURE.md §3.3, §5.2.0).
 *
 * This is the higher-risk of the two fixtures. The capability-grant format is
 * pre-existing and already exercised elsewhere; the rule-set format was invented
 * for this feature, so *nothing* would catch a disagreement between
 * `packages/controlplane/lib/proxy-rules.ts` and
 * `vaultysclaw-sensor/internal/rules` except this file. A field name the Go side
 * decodes to a zero value is a rule that silently does not apply — and a `deny`
 * rule that does not apply is an enforcement failure with no error anywhere.
 *
 * Uses the same fixed throwaway key as the grant fixture, so a host can pin one
 * anchor and verify both.
 *
 * Run from the repo root:
 *
 *     pnpm tsx conformance/generate-rules-fixture.ts
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { VaultysId, crypto as vaultysCrypto } from "@vaultys/id";
import {
  PROXY_RULESET_VERSION,
  signProxyRuleSet,
  type ProxyRuleSet,
} from "../packages/controlplane/lib/proxy-rules";

/** Same deterministic throwaway key as generate-grant-fixture.ts. */
const TEST_SECRET_SEED = Buffer.alloc(32, 0x2a);

const OUT_PATH = fileURLToPath(new URL("./rules-fixture.json", import.meta.url));

async function main() {
  const server = await VaultysId.machineFromEntropy(TEST_SECRET_SEED);

  // Deliberately exercises every dimension the wire format has: all three
  // subjects, both effects, a workloadId, a ports restriction, an exact host and
  // a dot-prefixed suffix, and a rule with the optional fields omitted.
  const set: ProxyRuleSet = {
    version: PROXY_RULESET_VERSION,
    issuedAt: Date.UTC(2026, 7, 6, 12, 0, 0),
    rules: [
      {
        id: "deny-openai-everywhere",
        subject: "any",
        hosts: ["openai.com", ".openai.com"],
        effect: "deny",
      },
      {
        id: "agents-no-internal",
        subject: "agent",
        hosts: [".internal.example"],
        ports: [443, 8443],
        effect: "deny",
      },
      {
        id: "claude-github-allowed",
        subject: "workload",
        workloadId: "wl-claude-code",
        hosts: ["api.github.com"],
        effect: "allow",
      },
    ],
  };

  const token = await signProxyRuleSet(server, set);

  const fixture = {
    $comment: [
      "Generated by conformance/generate-rules-fixture.ts — do not hand-edit.",
      "A proxy rule set signed by packages/controlplane/lib/proxy-rules.ts,",
      "verified by vaultysclaw-sensor/internal/rules (see fixture_test.go).",
      "Pins the msgpack key names, the subject/effect vocabularies, and which",
      "optional fields are omitted rather than sent as null.",
      "The signing key is a fixed throwaway test key and grants nothing real.",
    ],
    version: 1,
    serverIdBase64: vaultysCrypto.Buffer.from(server.id).toString("base64"),
    serverDid: server.did,
    token,
    expectedSet: set,
  };

  writeFileSync(OUT_PATH, `${JSON.stringify(fixture, null, 2)}\n`);
  console.log(`wrote ${OUT_PATH}`);
  console.log(`  ${set.rules.length} rules, token ${token.length} chars`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
