/**
 * Regenerates conformance/grant-fixture.json — a real capability-grant
 * certificate, signed by the TypeScript implementation, for the Go verifier to
 * check (docs/PROXY_ARCHITECTURE.md §3.3).
 *
 * Why a committed fixture rather than a live cross-language test: the Go
 * interception point must verify tokens that packages/policy produced, and
 * nothing else in either test suite proves the two agree on the wire format.
 * A Go-only round trip would pass even if Go used a different base64 variant,
 * different msgpack key casing, or a different signing scheme than the control
 * plane actually emits — every one of which would fail in production and in no
 * test.
 *
 * The identity is derived from a fixed secret so the fixture's public key is
 * stable across regenerations. It is a throwaway test key: it signs nothing but
 * this fixture and must never be used anywhere else.
 *
 * Run from the repo root:
 *
 *     pnpm tsx conformance/generate-grant-fixture.ts
 *
 * Regenerate only when the wire format itself changes. `issuedAt` is a real
 * timestamp so the output is not byte-reproducible — that is fine, the fixture
 * is committed, not recomputed.
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { VaultysId, crypto as vaultysCrypto } from "@vaultys/id";
import {
  signCapabilityGrantCert,
  signCapabilityRequestCert,
  verifyCapabilityGrantCert,
  type AgentCapability,
  type CertScope,
  type ResourceLimits,
} from "@vaultysclaw/policy";

/** Deterministic throwaway test key — 32 bytes of 0x2a. Never use elsewhere. */
const TEST_SECRET_SEED = Buffer.alloc(32, 0x2a);

const OUT_PATH = fileURLToPath(new URL("./grant-fixture.json", import.meta.url));

async function main() {
  // A machine identity derived from fixed entropy: same key on every run, so
  // the Go fixture's pinned public key never has to be updated.
  const server = await VaultysId.machineFromEntropy(TEST_SECRET_SEED);
  const agentDid = "did:vaultys:test-proxy";

  const capabilities: AgentCapability[] = ["internet_access", "api_call"];
  const resourceLimits: ResourceLimits = {
    allowedDomains: ["api.openai.com", "api.anthropic.com"],
    maxRequestsPerHour: 600,
  };
  const scope: CertScope = { resourcePattern: "mcp://github/*", maxUses: 3 };

  // Grants embed the agent's own signed request verbatim as the co-signature,
  // so the fixture exercises a nested token too — not a simplified shape the
  // control plane never actually emits.
  const requestCert = await signCapabilityRequestCert(server, {
    agentDid,
    requestedCapabilities: capabilities,
    requestedResourceLimits: resourceLimits,
    requestedScope: scope,
    nonce: "fixture-nonce",
  });

  const certId = "fixture-cert-0001";
  const expiresAt = Date.UTC(2099, 0, 1);

  const token = await signCapabilityGrantCert(server, {
    certId,
    agentDid,
    workspaceId: null,
    grantedCapabilities: capabilities,
    resourceLimits,
    scope,
    requestCert,
    expiresAt,
  });

  // Sanity-check with our own verifier before writing: a fixture the producing
  // side rejects is worthless as a cross-language contract.
  const reopened = verifyCapabilityGrantCert(server, token);
  if (!reopened) throw new Error("the freshly signed grant failed its own verification");
  if (reopened.certId !== certId) throw new Error("certId did not round-trip");

  const fixture = {
    $comment: [
      "Generated by conformance/generate-grant-fixture.ts — do not hand-edit.",
      "A real packcert capability-grant certificate signed by packages/policy,",
      "verified by vaultysclaw-sensor/internal/grant's Go implementation",
      "(see fixture_test.go). Proves the two agree on the base64 variant, the",
      "4-byte-LE length prefix, the msgpack key names, and the signature scheme.",
      "The signing key is a fixed throwaway test key and grants nothing real.",
    ],
    version: 1,
    /** Standard base64 of VaultysId.id — what Go's vaultysid.FromID consumes. */
    serverIdBase64: vaultysCrypto.Buffer.from(server.id).toString("base64"),
    serverDid: server.did,
    token,
    /** What the Go side must decode out of the token, field for field. */
    expectedBody: {
      type: "capability_grant",
      certId,
      agentDid,
      workspaceId: null,
      grantedCapabilities: capabilities,
      resourceLimits,
      scope,
      issuedAt: reopened.issuedAt,
      expiresAt,
    },
  };

  writeFileSync(OUT_PATH, `${JSON.stringify(fixture, null, 2)}\n`);
  console.log(`wrote ${OUT_PATH}`);
  console.log(`  server DID: ${server.did}`);
  console.log(`  token: ${token.length} chars`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
