/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // ── Adaptive palette (50–950 auto-invert in dark mode) ──
        primary: {
          DEFAULT: "rgb(var(--primary-500) / <alpha-value>)",
          50: "rgb(var(--primary-50)  / <alpha-value>)",
          100: "rgb(var(--primary-100) / <alpha-value>)",
          200: "rgb(var(--primary-200) / <alpha-value>)",
          300: "rgb(var(--primary-300) / <alpha-value>)",
          400: "rgb(var(--primary-400) / <alpha-value>)",
          500: "rgb(var(--primary-500) / <alpha-value>)",
          600: "rgb(var(--primary-600) / <alpha-value>)",
          700: "rgb(var(--primary-700) / <alpha-value>)",
          800: "rgb(var(--primary-800) / <alpha-value>)",
          900: "rgb(var(--primary-900) / <alpha-value>)",
          950: "rgb(var(--primary-950) / <alpha-value>)",
        },
        secondary: {
          DEFAULT: "rgb(var(--secondary-500) / <alpha-value>)",
          50: "rgb(var(--secondary-50)  / <alpha-value>)",
          100: "rgb(var(--secondary-100) / <alpha-value>)",
          200: "rgb(var(--secondary-200) / <alpha-value>)",
          300: "rgb(var(--secondary-300) / <alpha-value>)",
          400: "rgb(var(--secondary-400) / <alpha-value>)",
          500: "rgb(var(--secondary-500) / <alpha-value>)",
          600: "rgb(var(--secondary-600) / <alpha-value>)",
          700: "rgb(var(--secondary-700) / <alpha-value>)",
          800: "rgb(var(--secondary-800) / <alpha-value>)",
          900: "rgb(var(--secondary-900) / <alpha-value>)",
          950: "rgb(var(--secondary-950) / <alpha-value>)",
        },
        success: {
          DEFAULT: "rgb(var(--success-500) / <alpha-value>)",
          50: "rgb(var(--success-50)  / <alpha-value>)",
          100: "rgb(var(--success-100) / <alpha-value>)",
          200: "rgb(var(--success-200) / <alpha-value>)",
          300: "rgb(var(--success-300) / <alpha-value>)",
          400: "rgb(var(--success-400) / <alpha-value>)",
          500: "rgb(var(--success-500) / <alpha-value>)",
          600: "rgb(var(--success-600) / <alpha-value>)",
          700: "rgb(var(--success-700) / <alpha-value>)",
          800: "rgb(var(--success-800) / <alpha-value>)",
          900: "rgb(var(--success-900) / <alpha-value>)",
          950: "rgb(var(--success-950) / <alpha-value>)",
        },
        warning: {
          DEFAULT: "rgb(var(--warning-500) / <alpha-value>)",
          50: "rgb(var(--warning-50)  / <alpha-value>)",
          100: "rgb(var(--warning-100) / <alpha-value>)",
          200: "rgb(var(--warning-200) / <alpha-value>)",
          300: "rgb(var(--warning-300) / <alpha-value>)",
          400: "rgb(var(--warning-400) / <alpha-value>)",
          500: "rgb(var(--warning-500) / <alpha-value>)",
          600: "rgb(var(--warning-600) / <alpha-value>)",
          700: "rgb(var(--warning-700) / <alpha-value>)",
          800: "rgb(var(--warning-800) / <alpha-value>)",
          900: "rgb(var(--warning-900) / <alpha-value>)",
          950: "rgb(var(--warning-950) / <alpha-value>)",
        },
        danger: {
          DEFAULT: "rgb(var(--danger-500) / <alpha-value>)",
          50: "rgb(var(--danger-50)  / <alpha-value>)",
          100: "rgb(var(--danger-100) / <alpha-value>)",
          200: "rgb(var(--danger-200) / <alpha-value>)",
          300: "rgb(var(--danger-300) / <alpha-value>)",
          400: "rgb(var(--danger-400) / <alpha-value>)",
          500: "rgb(var(--danger-500) / <alpha-value>)",
          600: "rgb(var(--danger-600) / <alpha-value>)",
          700: "rgb(var(--danger-700) / <alpha-value>)",
          800: "rgb(var(--danger-800) / <alpha-value>)",
          900: "rgb(var(--danger-900) / <alpha-value>)",
          950: "rgb(var(--danger-950) / <alpha-value>)",
        },
        neutral: {
          DEFAULT: "rgb(var(--neutral-500) / <alpha-value>)",
          50: "rgb(var(--neutral-50)  / <alpha-value>)",
          100: "rgb(var(--neutral-100) / <alpha-value>)",
          200: "rgb(var(--neutral-200) / <alpha-value>)",
          300: "rgb(var(--neutral-300) / <alpha-value>)",
          400: "rgb(var(--neutral-400) / <alpha-value>)",
          500: "rgb(var(--neutral-500) / <alpha-value>)",
          600: "rgb(var(--neutral-600) / <alpha-value>)",
          700: "rgb(var(--neutral-700) / <alpha-value>)",
          800: "rgb(var(--neutral-800) / <alpha-value>)",
          900: "rgb(var(--neutral-900) / <alpha-value>)",
          950: "rgb(var(--neutral-950) / <alpha-value>)",
        },
        background: {
          DEFAULT: "rgb(var(--background-50) / <alpha-value>)",
          50: "rgb(var(--background-50)  / <alpha-value>)",
          100: "rgb(var(--background-100) / <alpha-value>)",
          200: "rgb(var(--background-200) / <alpha-value>)",
          300: "rgb(var(--background-300) / <alpha-value>)",
          400: "rgb(var(--background-400) / <alpha-value>)",
          500: "rgb(var(--background-500) / <alpha-value>)",
          600: "rgb(var(--background-600) / <alpha-value>)",
          700: "rgb(var(--background-700) / <alpha-value>)",
          800: "rgb(var(--background-800) / <alpha-value>)",
          900: "rgb(var(--background-900) / <alpha-value>)",
          950: "rgb(var(--background-950) / <alpha-value>)",
        },
        foreground: {
          DEFAULT: "rgb(var(--foreground-900) / <alpha-value>)",
          50: "rgb(var(--foreground-50)  / <alpha-value>)",
          100: "rgb(var(--foreground-100) / <alpha-value>)",
          200: "rgb(var(--foreground-200) / <alpha-value>)",
          300: "rgb(var(--foreground-300) / <alpha-value>)",
          400: "rgb(var(--foreground-400) / <alpha-value>)",
          500: "rgb(var(--foreground-500) / <alpha-value>)",
          600: "rgb(var(--foreground-600) / <alpha-value>)",
          700: "rgb(var(--foreground-700) / <alpha-value>)",
          800: "rgb(var(--foreground-800) / <alpha-value>)",
          900: "rgb(var(--foreground-900) / <alpha-value>)",
          950: "rgb(var(--foreground-950) / <alpha-value>)",
        },
      },
      animation: {
        "gradient-shift": "gradient-shift 8s ease infinite",
        "fade-in": "fade-in 0.6s ease forwards",
        "slide-up": "slide-up 0.5s ease forwards",
      },
      keyframes: {
        "gradient-shift": {
          "0%, 100%": { backgroundPosition: "0% 50%" },
          "50%": { backgroundPosition: "100% 50%" },
        },
        "fade-in": {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
        "slide-up": {
          from: { opacity: "0", transform: "translateY(16px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
      },
    },
  },
  plugins: [require("@tailwindcss/typography")],
};
