/**
 * Canonical registry of all API routes exposed by the control plane.
 *
 * This file is the single source of truth for:
 *   - The route permission selector UI (API key creation modal)
 *   - The Swagger coverage check script (scripts/check-api-coverage.ts)
 *
 * AUTO-GENERATED by scripts/generate-route-registry.ts
 * Do not edit by hand — run `pnpm tsx scripts/generate-route-registry.ts` to regenerate.
 * When you add a new route, also add an entry here.
 */

export interface RouteEntry {
  /** Next.js-style path, e.g. "/api/agents/[did]" */
  path: string;
  /** Supported HTTP methods */
  methods: string[];
  /** Top-level group shown in the permission tree */
  group: string;
  /** Optional sub-group for nested display */
  subgroup?: string;
  /** Short description displayed in the UI and Swagger */
  description: string;
  /** If true, the route is accessible without any authentication */
  isPublic?: boolean;
}

export const ROUTE_REGISTRY: RouteEntry[] = [

  // ── System ─────────────────────────────────────────────────────────────
  {
    path: "/api/about",
    methods: ["GET"],
    group: "System",
    description: "Retrieve documentation content",
    isPublic: true,
  },
  {
    path: "/api/health",
    methods: ["GET"],
    group: "System",
    description: "Health check for the control plane",
    isPublic: true,
  },
  {
    path: "/api/setup/status",
    methods: ["GET"],
    group: "System",
    description: "Check which setup steps are completed",
    isPublic: true,
  },

  // ── Agents ─────────────────────────────────────────────────────────────
  {
    path: "/api/agents",
    methods: ["GET"],
    group: "Agents",
    description: "List agents with optional pagination and filters",
  },
  {
    path: "/api/agents/[did]",
    methods: ["GET", "PATCH", "DELETE"],
    group: "Agents",
    description: "Get detailed info for a single agent by DID",
  },
  {
    path: "/api/agents/[did]/chat-sessions",
    methods: ["GET"],
    group: "Agents",
    subgroup: "Agent details",
    description: "Retrieve chat sessions",
  },
  {
    path: "/api/agents/[did]/chat-sessions/[sessionId]",
    methods: ["GET"],
    group: "Agents",
    subgroup: "Agent details",
    description: "Retrieve full history for a session",
  },
  {
    path: "/api/agents/[did]/llm-config",
    methods: ["GET", "PUT", "DELETE"],
    group: "Agents",
    subgroup: "Agent details",
    description: "Retrieve stored LLM config with masked API key",
  },
  {
    path: "/api/agents/[did]/location",
    methods: ["PATCH"],
    group: "Agents",
    subgroup: "Agent details",
    description: "Set or clear the geographic location of an agent",
  },
  {
    path: "/api/agents/[did]/peers",
    methods: ["GET", "POST"],
    group: "Agents",
    subgroup: "Agent peers",
    description: "List agent peers or peer grants",
    isPublic: true,
  },
  {
    path: "/api/agents/[did]/peers/[grantId]",
    methods: ["GET", "DELETE"],
    group: "Agents",
    subgroup: "Agent peers",
    description: "Get peer grant details",
    isPublic: true,
  },
  {
    path: "/api/agents/[did]/realm-llm",
    methods: ["GET"],
    group: "Agents",
    subgroup: "Agent details",
    description: "Get the agent's realm LiteLLM routing options",
  },
  {
    path: "/api/agents/[did]/schedules",
    methods: ["POST"],
    group: "Agents",
    subgroup: "Agent details",
    description: "Upsert a schedule on an agent",
  },
  {
    path: "/api/agents/[did]/schedules/[id]",
    methods: ["DELETE"],
    group: "Agents",
    subgroup: "Agent details",
    description: "Delete a schedule on an agent",
  },
  {
    path: "/api/agents/[did]/skill/[skillId]",
    methods: ["PATCH"],
    group: "Agents",
    subgroup: "Agent details",
    description: "Update an agent's skill override",
  },
  {
    path: "/api/agents/[did]/skills",
    methods: ["GET", "PATCH"],
    group: "Agents",
    subgroup: "Agent details",
    description: "Get effective skill configuration for an agent",
  },
  {
    path: "/api/agents/[did]/task",
    methods: ["POST"],
    group: "Agents",
    subgroup: "Agent details",
    description: "Enqueue a task on an agent via WebSocket",
  },
  {
    path: "/api/agents/[did]/token-usage",
    methods: ["GET"],
    group: "Agents",
    subgroup: "Agent details",
    description: "Retrieve token usage history for an agent",
  },
  {
    path: "/api/agents/search",
    methods: ["GET"],
    group: "Agents",
    description: "Search for agents by name or DID",
  },

  // ── Registrations ──────────────────────────────────────────────────────
  {
    path: "/api/registrations",
    methods: ["GET"],
    group: "Registrations",
    description: "List all pending registrations and available capabilities",
  },
  {
    path: "/api/registrations/[id]/approve",
    methods: ["POST"],
    group: "Registrations",
    description: "Approve a pending registration with selected capabilities",
  },
  {
    path: "/api/registrations/[id]/reject",
    methods: ["POST"],
    group: "Registrations",
    description: "Reject a pending registration",
  },
  {
    path: "/api/registrations/batch",
    methods: ["POST"],
    group: "Registrations",
    description: "Reject multiple pending registrations at once",
  },

  // ── Intents ────────────────────────────────────────────────────────────
  {
    path: "/api/intents",
    methods: ["GET", "POST"],
    group: "Intents",
    description: "Send an intent to one or more agents",
  },

  // ── Workflows ──────────────────────────────────────────────────────────
  {
    path: "/api/workflow-approvals",
    methods: ["GET"],
    group: "Workflows",
    description: "Retrieve approval items for the logged-in user",
  },
  {
    path: "/api/workflow-runs",
    methods: ["GET"],
    group: "Workflows",
    description: "List workflow runs with optional pagination and filters",
  },
  {
    path: "/api/workflow-runs/[id]",
    methods: ["GET"],
    group: "Workflows",
    description: "Get a specific workflow run with its history and steps",
  },
  {
    path: "/api/workflows",
    methods: ["GET", "POST"],
    group: "Workflows",
    description: "Save a new workflow",
  },
  {
    path: "/api/workflows/[id]",
    methods: ["GET", "PATCH", "DELETE"],
    group: "Workflows",
    description: "Fetch a single workflow by ID",
  },
  {
    path: "/api/workflows/[id]/execute",
    methods: ["POST"],
    group: "Workflows",
    subgroup: "Workflow details",
    description: "Start a new workflow run",
  },
  {
    path: "/api/workflows/[id]/export",
    methods: ["GET"],
    group: "Workflows",
    subgroup: "Workflow details",
    description: "Export a workflow by ID",
  },
  {
    path: "/api/workflows/[id]/schedule",
    methods: ["GET", "POST", "DELETE"],
    group: "Workflows",
    subgroup: "Workflow details",
    description: "Retrieve the current schedule configuration for a workflow",
  },
  {
    path: "/api/workflows/import",
    methods: ["POST"],
    group: "Workflows",
    description: "Import a new workflow definition",
  },
  {
    path: "/api/workflows/runs/[runId]/history",
    methods: ["GET"],
    group: "Workflows",
    description: "Get complete execution history of a workflow run",
  },
  {
    path: "/api/workflows/runs/[runId]/status",
    methods: ["GET"],
    group: "Workflows",
    description: "Get the status of a workflow run",
  },
  {
    path: "/api/workflows/templates",
    methods: ["GET"],
    group: "Workflows",
    subgroup: "Templates",
    description: "Retrieve workflow templates",
  },
  {
    path: "/api/workflows/templates/[templateId]",
    methods: ["GET"],
    group: "Workflows",
    subgroup: "Templates",
    description: "Retrieve a workflow template by ID",
  },
  {
    path: "/api/workflows/test-seed",
    methods: ["POST"],
    group: "Workflows",
    description: "Create a test workflow with 4 real agents in sequence",
  },

  // ── Workflow Approvals ─────────────────────────────────────────────────
  {
    path: "/api/workflow-approvals/[id]/approve",
    methods: ["POST"],
    group: "Workflow Approvals",
    description: "Approve a pending workflow step",
  },
  {
    path: "/api/workflow-approvals/[id]/dismiss",
    methods: ["POST"],
    group: "Workflow Approvals",
    description: "Dismiss a workflow notification",
  },
  {
    path: "/api/workflow-approvals/[id]/reject",
    methods: ["POST"],
    group: "Workflow Approvals",
    description: "Reject a pending workflow step",
  },

  // ── Channels ───────────────────────────────────────────────────────────
  {
    path: "/api/bridges/teams/incoming",
    methods: ["POST"],
    group: "Channels",
    description: "Process incoming messages from Teams Bot Framework",
    isPublic: true,
  },
  {
    path: "/api/bridges/webhook/[bridgeId]/incoming",
    methods: ["POST"],
    group: "Channels",
    description: "Accepts inbound messages from external webhook sources",
    isPublic: true,
  },
  {
    path: "/api/channels",
    methods: ["GET", "POST"],
    group: "Channels",
    description: "List channels in a realm, optionally including global channels",
  },
  {
    path: "/api/channels/[id]",
    methods: ["GET", "PATCH", "DELETE"],
    group: "Channels",
    description: "Get channel details including members",
  },
  {
    path: "/api/channels/[id]/bridges",
    methods: ["GET", "POST"],
    group: "Channels",
    subgroup: "Bridges",
    description: "List all bridges for a channel",
  },
  {
    path: "/api/channels/[id]/bridges/[bridgeId]",
    methods: ["PATCH", "DELETE"],
    group: "Channels",
    subgroup: "Bridges",
    description: "Update syncDirection and/or isSyncEnabled for a bridge",
  },
  {
    path: "/api/channels/[id]/members",
    methods: ["POST", "DELETE"],
    group: "Channels",
    subgroup: "Channel details",
    description: "Add a member to a channel",
  },
  {
    path: "/api/channels/[id]/messages",
    methods: ["GET", "POST"],
    group: "Channels",
    subgroup: "Messages",
    description: "List messages in a channel or thread",
  },
  {
    path: "/api/channels/[id]/messages/[msgId]",
    methods: ["GET", "PATCH", "DELETE"],
    group: "Channels",
    subgroup: "Messages",
    description: "Get a specific message",
  },
  {
    path: "/api/channels/[id]/messages/[msgId]/reactions",
    methods: ["POST"],
    group: "Channels",
    subgroup: "Messages",
    description: "Add or remove a reaction to a message",
  },
  {
    path: "/api/channels/[id]/messages/agent-response",
    methods: ["POST"],
    group: "Channels",
    subgroup: "Messages",
    description: "Post an agent response to a channel or thread",
  },
  {
    path: "/api/channels/[id]/threads",
    methods: ["GET", "POST"],
    group: "Channels",
    subgroup: "Threads",
    description: "Create a threaded reply to a message",
  },

  // ── Users ──────────────────────────────────────────────────────────────
  {
    path: "/api/invitations/[token]",
    methods: ["GET"],
    group: "Users",
    description: "Retrieve invitation details using a token",
    isPublic: true,
  },
  {
    path: "/api/invitations/[token]/delete",
    methods: ["POST"],
    group: "Users",
    description: "Delete an invitation after it's been successfully claimed",
    isPublic: true,
  },
  {
    path: "/api/me/realms",
    methods: ["GET"],
    group: "Users",
    subgroup: "User details",
    description: "Get realms the current user belongs to",
  },
  {
    path: "/api/users",
    methods: ["GET"],
    group: "Users",
    description: "List registered users with optional pagination and filters",
  },
  {
    path: "/api/users/[did]",
    methods: ["GET", "PATCH", "DELETE"],
    group: "Users",
    description: "Get a single user by DID",
  },
  {
    path: "/api/users/[did]/admin",
    methods: ["PATCH"],
    group: "Users",
    subgroup: "User details",
    description: "Promote or demote a user to/from admin",
  },
  {
    path: "/api/users/[did]/grants",
    methods: ["GET", "POST"],
    group: "Users",
    subgroup: "User grants",
    description: "List grants for a user",
  },
  {
    path: "/api/users/[did]/grants/[id]",
    methods: ["DELETE"],
    group: "Users",
    subgroup: "User grants",
    description: "Revoke a delegation grant",
  },
  {
    path: "/api/users/[did]/location",
    methods: ["PATCH"],
    group: "Users",
    subgroup: "User details",
    description: "Set or clear the geographic location of a user",
  },
  {
    path: "/api/users/invite",
    methods: ["GET"],
    group: "Users",
    subgroup: "Invitations",
    description: "Create a registration certificate for a new user",
  },
  {
    path: "/api/users/invite/email",
    methods: ["POST"],
    group: "Users",
    subgroup: "Invitations",
    description: "Send an email invitation to a new user",
  },
  {
    path: "/api/users/invite/from-email",
    methods: ["POST"],
    group: "Users",
    subgroup: "Invitations",
    description: "Generate QR code from an email invitation token",
    isPublic: true,
  },
  {
    path: "/api/users/me",
    methods: ["GET", "PATCH"],
    group: "Users",
    description: "Return the current user's profile",
  },
  {
    path: "/api/users/search",
    methods: ["GET"],
    group: "Users",
    description: "List users in a realm with optional search by name/email",
    isPublic: true,
  },
  {
    path: "/api/users/unclaimed/[id]",
    methods: ["GET", "PATCH", "DELETE"],
    group: "Users",
    subgroup: "Unclaimed users",
    description: "Get an unclaimed Entra user by internal ID",
  },
  {
    path: "/api/users/unclaimed/[id]/send-qr",
    methods: ["POST"],
    group: "Users",
    subgroup: "Unclaimed users",
    description: "Send a QR code to an unclaimed user via email",
  },

  // ── Realms ─────────────────────────────────────────────────────────────
  {
    path: "/api/realms",
    methods: ["GET", "POST"],
    group: "Realms",
    description: "List realms with counts of agents, users, and workflows",
  },
  {
    path: "/api/realms/[id]",
    methods: ["GET", "PATCH", "DELETE"],
    group: "Realms",
    description: "Retrieve details of a specific realm",
  },
  {
    path: "/api/realms/[id]/agents",
    methods: ["POST", "DELETE"],
    group: "Realms",
    subgroup: "Realm members",
    description: "Add an agent to a realm",
  },
  {
    path: "/api/realms/[id]/credentials",
    methods: ["GET", "POST", "DELETE"],
    group: "Realms",
    subgroup: "Credentials",
    description: "List credential metadata for a realm",
  },
  {
    path: "/api/realms/[id]/credentials/[credId]",
    methods: ["GET"],
    group: "Realms",
    subgroup: "Credentials",
    description: "Retrieve the plaintext secret for a specific credential",
  },
  {
    path: "/api/realms/[id]/default",
    methods: ["POST"],
    group: "Realms",
    subgroup: "Realm members",
    description: "Set a realm as the default",
  },
  {
    path: "/api/realms/[id]/models",
    methods: ["GET"],
    group: "Realms",
    subgroup: "Realm members",
    description: "List models available to a realm along with router key info",
  },
  {
    path: "/api/realms/[id]/skills",
    methods: ["GET", "POST"],
    group: "Realms",
    subgroup: "Realm skills",
    description: "List all skills defined for a realm",
  },
  {
    path: "/api/realms/[id]/skills/[skillId]",
    methods: ["GET", "PATCH", "DELETE"],
    group: "Realms",
    subgroup: "Realm skills",
    description: "Retrieve skill details by skill ID",
  },
  {
    path: "/api/realms/[id]/social-media",
    methods: ["POST"],
    group: "Realms",
    subgroup: "Realm members",
    description: "Dispatch a social media post intent to an online agent",
  },
  {
    path: "/api/realms/[id]/users",
    methods: ["POST", "PATCH", "DELETE"],
    group: "Realms",
    subgroup: "Realm members",
    description: "Add a user to a realm",
  },

  // ── Models ─────────────────────────────────────────────────────────────
  {
    path: "/api/models",
    methods: ["GET", "POST"],
    group: "Models",
    description: "List all model registry entries",
  },
  {
    path: "/api/models/[id]",
    methods: ["GET", "PUT", "DELETE"],
    group: "Models",
    description: "Retrieve a model by its ID",
  },
  {
    path: "/api/models/[id]/realms",
    methods: ["GET", "POST", "DELETE"],
    group: "Models",
    subgroup: "Model details",
    description: "List realms with access to a specific model",
  },
  {
    path: "/api/models/[id]/validate",
    methods: ["POST"],
    group: "Models",
    subgroup: "Model details",
    description: "Validate connectivity to a model's endpoint",
  },
  {
    path: "/api/models/test",
    methods: ["POST"],
    group: "Models",
    description: "Test connectivity to a model endpoint and fetch available models",
  },

  // ── Skills ─────────────────────────────────────────────────────────────
  {
    path: "/api/org/skills",
    methods: ["GET", "POST"],
    group: "Skills",
    subgroup: "Org skills",
    description: "List the organization skill catalog",
  },
  {
    path: "/api/org/skills/[id]",
    methods: ["GET", "PATCH", "DELETE"],
    group: "Skills",
    subgroup: "Org skills",
    description: "Retrieve a specific organization skill by ID",
  },
  {
    path: "/api/skills",
    methods: ["GET", "POST"],
    group: "Skills",
    description: "Retrieve all skills with their associated realms",
  },
  {
    path: "/api/skills/library",
    methods: ["GET"],
    group: "Skills",
    subgroup: "Library",
    description: "Retrieve the organisation's skill catalog",
  },
  {
    path: "/api/skills/library/content",
    methods: ["GET"],
    group: "Skills",
    subgroup: "Library",
    description: "Retrieve markdown instructions for an organization skill by name",
  },

  // ── Governance ─────────────────────────────────────────────────────────
  {
    path: "/api/governance/audit",
    methods: ["GET"],
    group: "Governance",
    subgroup: "Audit log",
    description: "Retrieve a unified audit stream of activity and intent logs",
  },
  {
    path: "/api/governance/audit/[id]",
    methods: ["GET"],
    group: "Governance",
    subgroup: "Audit log",
    description: "Retrieve a single audit entry with full details and metadata",
  },
  {
    path: "/api/governance/summary",
    methods: ["GET"],
    group: "Governance",
    description: "*   get:",
  },
  {
    path: "/api/policies",
    methods: ["GET", "POST"],
    group: "Governance",
    description: "List all policies",
  },
  {
    path: "/api/policies/[id]",
    methods: ["GET", "DELETE"],
    group: "Governance",
    description: "Retrieve a policy by ID",
  },
  {
    path: "/api/tool-approvals",
    methods: ["GET", "POST"],
    group: "Governance",
    description: "List pending tool approval requests",
  },

  // ── Knowledge ──────────────────────────────────────────────────────────
  {
    path: "/api/knowledge",
    methods: ["GET", "POST"],
    group: "Knowledge",
    description: "List knowledge sources",
  },
  {
    path: "/api/knowledge/[id]",
    methods: ["GET", "DELETE"],
    group: "Knowledge",
    description: "Retrieve a knowledge source by ID",
  },
  {
    path: "/api/knowledge/[id]/sync",
    methods: ["POST"],
    group: "Knowledge",
    description: "Initiate a sync for a knowledge source",
  },
  {
    path: "/api/knowledge/files",
    methods: ["GET", "POST"],
    group: "Knowledge",
    subgroup: "Files",
    description: "List file metadata for a knowledge source",
  },
  {
    path: "/api/knowledge/files/[fileId]",
    methods: ["DELETE"],
    group: "Knowledge",
    subgroup: "Files",
    description: "Delete a knowledge file by ID",
  },

  // ── Server ─────────────────────────────────────────────────────────────
  {
    path: "/api/server",
    methods: ["GET"],
    group: "Server",
    description: "Retrieve server identity, status, and system info",
    isPublic: true,
  },
  {
    path: "/api/server/entra",
    methods: ["GET", "POST", "PUT"],
    group: "Server",
    subgroup: "Entra ID",
    description: "Retrieve the Entra configuration with secrets redacted",
  },
  {
    path: "/api/server/entra/send-qr",
    methods: ["POST"],
    group: "Server",
    subgroup: "Entra ID",
    description: "Send QR code to Entra ID user",
    isPublic: true,
  },
  {
    path: "/api/server/entra/sync",
    methods: ["POST"],
    group: "Server",
    subgroup: "Entra ID",
    description: "Trigger a user sync from Microsoft Entra ID",
  },
  {
    path: "/api/server/entra/unclaimed",
    methods: ["GET"],
    group: "Server",
    subgroup: "Entra ID",
    description: "List unclaimed Entra-provisioned users",
  },
  {
    path: "/api/server/settings",
    methods: ["GET", "PUT"],
    group: "Server",
    description: "Retrieve server connection settings",
  },
  {
    path: "/api/server/smtp",
    methods: ["GET", "POST", "PUT"],
    group: "Server",
    subgroup: "SMTP",
    description: "Retrieve SMTP configuration with password redacted",
  },
  {
    path: "/api/settings/docling",
    methods: ["GET", "PUT"],
    group: "Server",
    subgroup: "Docling",
    description: "Retrieve the Docling configuration settings",
  },
  {
    path: "/api/settings/docling/location",
    methods: ["PATCH"],
    group: "Server",
    subgroup: "Docling",
    description: "Update or clear Docling service location on maps",
  },
  {
    path: "/api/settings/docling/test",
    methods: ["POST"],
    group: "Server",
    subgroup: "Docling",
    description: "Test and discover Docling endpoints",
  },
  {
    path: "/api/settings/storage",
    methods: ["GET", "PUT"],
    group: "Server",
    subgroup: "Storage",
    description: "Retrieve the current storage configuration",
  },
  {
    path: "/api/settings/storage/location",
    methods: ["PATCH"],
    group: "Server",
    subgroup: "Storage",
    description: "Update or clear object-storage location on infrastructure maps",
  },
  {
    path: "/api/settings/storage/migrate",
    methods: ["POST"],
    group: "Server",
    subgroup: "Storage",
    description: "Migrate files from SQLite BLOB storage to filesystem/S3 storage",
  },
  {
    path: "/api/settings/storage/test",
    methods: ["POST"],
    group: "Server",
    subgroup: "Storage",
    description: "Test storage settings with optional overrides",
  },

  // ── Network ────────────────────────────────────────────────────────────
  {
    path: "/api/graph",
    methods: ["GET"],
    group: "Network",
    description: "Retrieve the full relationship graph of nodes and edges",
  },
  {
    path: "/api/map",
    methods: ["GET"],
    group: "Network",
    description: "Aggregate all located entities into map markers",
  },
  {
    path: "/api/network",
    methods: ["GET", "POST"],
    group: "Network",
    description: "Retrieve live transport stats and server state",
  },

  // ── Stats ──────────────────────────────────────────────────────────────
  {
    path: "/api/stats/tokens",
    methods: ["GET"],
    group: "Stats",
    description: "Retrieve token usage statistics",
  },

  // ── Chat ───────────────────────────────────────────────────────────────
  {
    path: "/api/chat",
    methods: ["POST"],
    group: "Chat",
    description: "Stream a chat response from a connected agent",
  },

  // ── API Keys ───────────────────────────────────────────────────────────
  {
    path: "/api/api-keys",
    methods: ["GET", "POST"],
    group: "API Keys",
    description: "List API keys",
  },
  {
    path: "/api/api-keys/[id]",
    methods: ["PATCH", "DELETE"],
    group: "API Keys",
    description: "Update an API key",
  },
];

/** Convenience helper: get unique group names in the order they appear */
export function getRouteGroups(): string[] {
  return [
    ...new Set(ROUTE_REGISTRY.filter((r) => !r.isPublic).map((r) => r.group)),
  ];
}

/** Get all non-public routes for a given group */
export function getRoutesByGroup(group: string): RouteEntry[] {
  return ROUTE_REGISTRY.filter((r) => r.group === group && !r.isPublic);
}
